 <footer class="container-fluid text-center">
    <p>Siguenos en las Redes Sociales</p>
    <a href="https://www.facebook.com/"><img class="botonera" src="img/face.png" alt="cabecera" /></a>
    <a href="https://www.instagram.com/?hl=es"><img class="botonera" src="img/ins.png" alt="cabecera" /></a>
    <a href="https://twitter.com/"><img class="botonera" src="img/twi.png" alt="cabecera" /></a>
    <p class="footer">Practicas DAW - Copyright © 2019.</p>
  </footer>