<header>
    <img class="header" src="img/header.jpg">
  </header>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="http://www.aprendeahackear.com/">
          <img class="logo" src="img/pc.jpg">
        </a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li class="active"><a href="Index.php">Inicio</a></li>
          <li><a href="PaginaPhp.php">PHP</a></li>
          <li><a href="PaginaJavascript.php">JAVASCRIPT</a></li>
        </ul>
      </div>
    </div>
  </nav>