 
 <div class="container-fluid text-center">
    <div class="container-fluid" class="pagination justify-content-center">
                    <ul class="pagination">
                        <li><a href="Index.php">Inicio</a></li>
                        <li><a href="PaginaPhp.php">2</a></li>
                        <li><a href="PaginaJavascript.php">3</a></li>
                        <li><a href="PaginaJavascript.php">Última</a></li>
                    </ul>
    </div>
 </div>